name: Backend CD

on:
    workflow_run:
        workflows: ["Backend CI"]
        types: ["completed"]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Pull Docker Image
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/freshcutz-api

            - name: Stop and Remove Container
              run: docker stop freshcutz-api && docker rm freshcutz-api || true

            - name: Run Container
              run: docker run -d --name freshcutz-api -p 80:4000 ${{ secrets.DOCKER_USERNAME }}/freshcutz-api
