name: Web CD

on:
    workflow_run:
        workflows: ["Web CI"]
        types: ["completed"]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Pull Docker Image
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/freshcutz-web

            - name: Stop and Remove Container
              run: docker stop freshcutz-web && docker rm freshcutz-web || true

            - name: Run Container
              run: docker run -d --name freshcutz-web -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/freshcutz-web
